Importing **numpy**

In [1]:
import numpy as np

**Exercise 1:**

Create a 1D array with values ranging from 0 to 9.

In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Exercise 2:**

Convert a 1D array to a 2D array with 2 rows.

In [3]:
arr = np.array([1,2,3,4,5,6]).reshape(2,-1)
arr

array([[1, 2, 3],
       [4, 5, 6]])

**Exercise 3:**

Multiply a 5x3 matrix by a 3x2 matrix.

In [4]:
arr1 = np.arange(15).reshape((5,3))
arr2 = np.arange(6).reshape((3,2))

prod = np.dot(arr1, arr2)

print("Arr1: ",arr1)
print("Arr2: ",arr2)
print("Prod: ",prod)

Arr1:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Arr2:  [[0 1]
 [2 3]
 [4 5]]
Prod:  [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


**Exercise 4:**

Extract all odd numbers from an array of 1-10.

In [5]:
arr = np.arange(10)

odd_arr = arr[arr%2==1]

odd_arr

array([1, 3, 5, 7, 9])

**Exercise 5:**

Replace all odd numbers in an array of 1-10 with -1.

In [6]:
arr = np.arange(1,10)
arr[arr%2 == 1] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

**Exercise 6:**

Convert a 1D array to a boolean array where all positive values become True.

In [7]:
arr = np.array([1,-2,3,-4,5,-6])

bool_arr = arr > 0

bool_arr

array([ True, False,  True, False,  True, False])

**Exercise 7:**

Replace all even numbers in a 1D array with their negative

In [8]:
arr = np.arange(1,20)

arr[arr%2==0] *= -1

arr

array([  1,  -2,   3,  -4,   5,  -6,   7,  -8,   9, -10,  11, -12,  13,
       -14,  15, -16,  17, -18,  19])

**Exercise 8:**

Create a random 3x3 matrix and normalize it.

In [9]:
matrix = np.random.random((3,3))

print(matrix)

normalized_matrix = (matrix - np.mean(matrix))/np.std(matrix)

print(normalized_matrix)

[[0.71906128 0.918992   0.59360107]
 [0.42465542 0.17065466 0.02433045]
 [0.08145528 0.32314297 0.61897399]]
[[ 0.99952984  1.69215557  0.56489442]
 [-0.02038888 -0.90033099 -1.40724617]
 [-1.20934699 -0.37206138  0.65279456]]


**Exercise 9:**

Calculate the sum of the diagonal elements of a 3x3 matrix.

In [10]:
arr = np.arange(1,10).reshape(3,3)

print(arr)

diagonal_sum = np.trace(arr)

print(diagonal_sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


**Exercise 10:**

Find the indices of non-zero elements from [1,2,0,0,4,0].

In [11]:
arr = np.array([1,2,0,0,4,0])

non_zero_indices = np.nonzero(arr)

non_zero_indices

(array([0, 1, 4]),)

**Exercise 11:**

Reverse a 1D array (first element becomes the last).

In [12]:
arr = np.arange(1,10)

arr = np.flip(arr)

arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

**Exercise 12:**

Create a 3x3 identity matrix

In [13]:
identity = np.eye(3)

identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Exercise 13:**

Reshape a 1D array to a 2D array with 5 rows and 2 columns.

In [14]:
arr = np.arange(10).reshape(5,2)

arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**Exercise 14:**

Stack two arrays vertically.

In [15]:
arr1 = np.array([1,2,3,4,5,6])

arr2 = np.array([3,4,5,7,4,6])

stacked_array = np.vstack((arr1,arr2))

stacked_array

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 7, 4, 6]])

**Exercise 15:**

Get the common items between two arrays.

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([3, 4, 5, 6, 7])

common_items = np.intersect1d(arr1, arr2)

print(common_items)

[3 4 5]


**Exercise 16:**

Create a 5x5 matrix with row values ranging from 0 to 4.

In [17]:
matrix = np.zeros((5,5))

matrix += np.array([0,1,2,3,4])

matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

**Exercise 17:**

Find the index of the maximum value in a 1D array.

In [18]:
arr = np.array([1,2,3,4,5,6,67,8,9])

max_index = np.argmax(arr)

max_index

np.int64(6)

**Exercise 18:**

Normalize the values in a 1D array between 0 and 1.

In [19]:
arr = np.array([2, 5, 8, 9, 12, 56])

normalized_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print(normalized_arr)

[0.         0.05555556 0.11111111 0.12962963 0.18518519 1.        ]


**Exercise 19:**

Calculate the dot product of two arrays

In [20]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)

print(dot_product)

32


**Exercise 20:**

Count the number of elements in an array within a specific range.

In [21]:
arr = np.array([1,2,3,4,5,6,45,7,7,5,4,4,5,3,4,4,4,7,7,6,8,9,0])

count_within_range = np.sum((arr>=5) & (arr<=9))

count_within_range

np.int64(11)

**Exercise 21:**

Find the mean of each row in a 2D array.

In [22]:
arr = np.arange(15).reshape(3,5)

mean = np.mean(arr, axis=1)

mean

array([ 2.,  7., 12.])

**Exercise 22:**

Create a random 4x4 matrix and extract the diagonal elements.

In [23]:
arr = np.arange(16).reshape(4,4)

print(arr)

diagonal_elements = np.diag(arr)

print(diagonal_elements)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]


**Exercise 23:**

Count the number of occurrences of a specific value in an array.

In [24]:
def countSpecificNum(arr, num):
    return np.sum((arr==num))

arr = np.array([1,2,13,4,5,34,6,7,8,5,44,6,45,4,4,3,22,2,2,2])

print(countSpecificNum(arr, 2))

4


**Exercise 24:**

Replace all values in a 1D array with the mean of the array.

In [25]:
arr = np.array([1,2,13,4,5,34,6,7,8,5,44,6,45,4,4,3,22,2,2,2])

arr[:] = np.mean(arr)

print(arr)

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


**Exercise 25:**

Find the indices of the maximum and minimum values in a 1D array.

In [26]:
arr = np.array([1,2,4,3,546,45,634,324,2,234,5,3,35,65,6,7,5,34,34,6,36,36,36,3,74,86,85])

min = np.argmin(arr)

max = np.argmax(arr)

print(min, max)

0 6


**Exercise 26:**

Create a 2D array with 1 on the border and 0 inside.

In [27]:
arr = np.ones((5,5))

arr[1:-1, 1:-1] = 0

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Exercise 27:**

Find the unique values and their counts in a 1D array.

In [28]:
arr = np.array([1,2,1,33,1,3,3,4,3,4,5,6,4,5,6,5,3,3,53,3,2,4,3,2,2])

unique, counts = np.unique(arr, return_counts=True)

print(unique)

print(counts)

[ 1  2  3  4  5  6 33 53]
[3 4 7 4 3 2 1 1]


**Exercise 28:**

Create a 3x3 matrix with values ranging from 0 to 8.

In [29]:
arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Exercise 29:**

Calculate the exponential of all elements in a 1D array.

In [30]:
arr = np.array([1, 2, 3, 4, 5])

exponential_arr = np.exp(arr)

print(exponential_arr)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


**Exercise 30:**

Swap two rows in a 2D array.

In [31]:
arr = np.array(range(15)).reshape(3,5)

arr[[1,2]] = arr[[2,1]]

arr

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

**Exercise 31:**

Create a random 3x3 matrix and replace all values greater than 0.5 with 1 and all others with 0.

In [32]:
arr = np.random.random((3,3))

arr[arr > 0.5] = 1

arr[arr <=0.5] = 0

arr

array([[1., 1., 1.],
       [1., 0., 1.],
       [0., 0., 0.]])

**Exercise 32:**

Find the indices of the top N maximum values in a 1D array.

In [33]:
arr = np.array([1,2,3,345,4,6,5,4,3,3,5,3,3,42,41,2,5,2])

top_indices = np.argsort(arr)[-5:]

top_indices

array([10,  5, 14, 13,  3])

**Exercise 33:**

Calculate the mean of each column in a 2D array.


In [34]:
matrix = np.arange(15).reshape(5,3)

print(matrix)

column_means = np.mean(matrix, axis=0)

print(column_means)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[6. 7. 8.]


**Exercise 34:**

Normalize the values in each column of a 2D array.

In [35]:
matrix = np.arange(15).reshape(5,3)

print(matrix)

normalized_matrix = (matrix - np.mean(matrix, axis=0))/np.std(matrix,axis=0)

print(normalized_matrix)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


**Exercise 35:**

Concatenate two 1D arrays.

In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

concatenated_arr = np.concatenate((arr1, arr2))

print(concatenated_arr)

[1 2 3 4 5 6]


**Exercise 36:**

Create a 2D array with random values and sort each row.

In [37]:
arr = np.array([1,2,4,5,43,3,2,4,4,2,2,1,1,1,4,6,7,4]).reshape(2,-1)

print(arr)

sorted_arr = np.sort(arr, axis=1)

print(sorted_arr)

[[ 1  2  4  5 43  3  2  4  4]
 [ 2  2  1  1  1  4  6  7  4]]
[[ 1  2  2  3  4  4  4  5 43]
 [ 1  1  1  2  2  4  4  6  7]]


**Exercise 37:**

Compute the mean squared error between two arrays.

In [38]:
arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([2, 3, 4, 5])

mse = np.mean((arr1-arr2)**2)

print(mse)

1.0


**Exercise 38:**

Replace all negative values in an array with 0.

In [39]:
arr = np.array([1,2,1,3,2,2,3,-1,-3,-53,43,3,4,3,3,-45,2])

arr[arr<0] = 0

arr

array([ 1,  2,  1,  3,  2,  2,  3,  0,  0,  0, 43,  3,  4,  3,  3,  0,  2])

**Exercise 39:**

Find the 5th and 95th percentiles of an array.

In [40]:
arr = np.array([1,2,2,4,4,3,4,3,2,4,5,6,6,5,7,8,9,9,7,6,5,5,5])

percentile_5th = np.percentile(arr, 5)

percentile_95th = np.percentile(arr, 95)

print("5th Percentile:", percentile_5th)

print("95th Percentile:", percentile_95th)

5th Percentile: 2.0
95th Percentile: 8.899999999999999


**Exercise 40:**

Create a random 2x2 matrix and compute its determinant.

In [41]:
matrix = np.random.random((3,3))

det = np.linalg.det(matrix)

det

np.float64(-0.03230036459816969)

**Exercise 41:**

Count the number of elements in an array that are greater than the mean.

In [42]:
arr = np.arange(10)

mean = np.mean(arr)

count_above_mean = np.sum(arr > mean)

count_above_mean

np.int64(5)

**Exercise 42:**

Calculate the square root of each element in a 1D array.

In [43]:
arr = np.arange(10)

sqrt_arr = np.sqrt(arr)

sqrt_arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

**Exercise 43:**

Create a 3x3 matrix and compute the matrix square root.

In [44]:
matrix = np.arange(9).reshape(3,3)

matrix_sqrt = np.linalg.matrix_power(matrix, 2)

matrix_sqrt

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

**Exercise 44:**

Convert the data type of an array to float.

In [45]:
arr = np.array([1, 2, 3, 4], dtype=int)

float_arr = arr.astype(float)

print(float_arr)

[1. 2. 3. 4.]


**Exercise 45:**

Calculate the element-wise absolute values of an array.

In [46]:
arr = np.random.random(10)

arr = np.abs(arr)

arr

array([0.34612445, 0.75750318, 0.88812401, 0.70513605, 0.17793196,
       0.5843462 , 0.04915426, 0.55194822, 0.49971222, 0.57484533])